### ISSUE TITLE
Attempted import error: 'ViewUpcastWriter' is not exported from '@ckeditor/ckeditor5-engine/dist/index.js' (imported as 'ViewUpcastWriter').

### ISSUE THREAD

**Issue by pawan-khade** [wiris/html-integrations#1112]
today all of sudden i am encountering this issue in my @wiris/mathtype-ckeditor5 react plugin. till yesterday it was working. is ViewUpcastWriter not getting imported or moved or removed?

**Comment by carla-at-wiris** [comment]
Hello @pawan-khade, thank you for reaching us.

Could you share which versions of CKEditor 5 and MathType for CKEditor 5 are you using?

CKEditor 5 did a release recently, `v46` in which they updated this dependency. Yesterday, we updated our packages to be compatible with their latest release, so knowing which versions you are using will be a big help for us to solve your problem. Thanks!

**Comment by pawan-khade** [comment]
Hello @carla-at-wiris ,
 thanks for reaching out early for solving problem,
I have specified the ckeditor and mathtype version. My critical functionality is not working right now because of this problem can you pease help me out with this?  I also upgraded ckeditor and mathtype to latest versions of 26 and 8.13.3 respectively but still getting same problem.

**Comment by carla-at-wiris** [comment]
Hi @pawan-khade,

We would need a bit more information on your issue and how to reproduce it. The method you mentioned is being imported properly on our plugin, as you can see in `packages/ckeditor5/src/plugin.js`.
