### ISSUE TITLE
onChange event is getting called, but with no data, when content is added via plugin like mathtype or wiris 

### ISSUE THREAD

**Issue by dcanetma** [wiris/html-integrations#115]
## Provide detailed reproduction steps (if any)

> Originally reported at: https://github.com/ckeditor/ckeditor4/issues/4280 

Creating new issue from previous issue.
Reference:
#3817

1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html

2. Handle 'change' event of editor, paste in dev console:

`CKEDITOR.instances.editor1.on( 'change', function() { console.log( 'change event data', this.getData() ); } );`

1. Delete all content in ckeditor

2. Launch mathtype from the editor

3. Add math formula and click insert

4. Editor 'change event is fired, when you click insert button on mathtype.

5. call editor.getData(), returns empty result

6. Formula is is inserted into ckeditor.

### Expected result

when call step 7 above, expected to get the mathml code as data
### Actual result

returns nothing, believe event get fired before data is inserted into ckeditor and not after.
## Other details

* Browser: Chrome(latest)

* OS: Windows 10

* CKEditor version: latest

* Installed CKEditor plugins: MathType

**Comment by nileshsonkusare-SQT** [comment]
I also facing this issue with mathtype plugin. Please fix this issue ASAP...

**Comment by henok-tesfaye** [comment]
Any update on this? Thanks!

**Comment by dcanetma** [comment]
Thanks for reporting the bug.

We are working on it.

Keep you posted.

**Comment by dcanetma** [comment]
Our next release is planned on the next hours.

**Comment by henok-tesfaye** [comment]
Thank you.

**Comment by carlawiris** [comment]
we have released a new version that corrects this bug, it is the 7.24.1

**Comment by henok-tesfaye** [comment]
Thank you, but I think the [demo page](https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html) still uses the old version.

**Comment by dcanetma** [comment]
You are right.

The demo pages on the wiris.com will be upgraded in the next hours.

We just wanted to inform that latest version of the npm package for the MathType  integration on CKEditor is available.

**Comment by AmmarAlhabibACD** [comment]
I am using external integration, and still facing this issue, is there any way to fix it for those who use external integration?

**Comment by dcanetma** [comment]
@AmmarAlhabibACD This bug should be fixed for both external and same-server integration on our last release.

**Comment by dcanetma** [comment]
@AmmarAlhabibACD For your convenience, we've created this video reproducing the expected behaviour as described on the 

[https://drive.google.com/file/d/1GuqJvc_DtSHAvQYs8ADzLTr3vVAbkSWf/view?usp=sharing](https://drive.google.com/file/d/1GuqJvc_DtSHAvQYs8ADzLTr3vVAbkSWf/view?usp=sharing)

The demo website used is included on the very same MathType API on this address: [https://www.wiris.net/demo/plugins/tests/ckeditor/index.html](https://www.wiris.net/demo/plugins/tests/ckeditor/index.html)

This is the code used for the event change:

````Javascript
CKEDITOR.instances.example.on( 'change', function() { console.log( 'Hooray! Changed event data', this.getData() ); } );
````
.

**Comment by AmmarAlhabibACD** [comment]
@dcanetma  
**Now I have realized what is the issue exactly in my side, so anyone might find these details helpful:**

Yup, it is working fine on the URL above as expected. And also it is working fine with me, but please let me describe my issue in details:

Actually, in my development process last month I was using this URL for external integration:

`CKEDITOR.plugins.addExternal('ckeditor_wiris', 'https://www.wiris.net/demo/plugins/ckeditor/', 'plugin.js');`

It was working fine as expected
Note : it is using /demo/ path.

- And when I deployed to the test server, the 'Trial version' message appear.
- Then we ask Wiris team to teach us how to install the license to get that message removed.
- They said that "Just change the word 'demo' in the path to 'client'.
- I changed it to be
 `CKEDITOR.plugins.addExternal('ckeditor_wiris', 'https://www.wiris.net/client/plugins/ckeditor/', 'plugin.js');`

- I asked them to clarify how they will detect our license if I only do that change, they didn't justify, and they said just changed it and it will be gon.
- I did the change, but unfortunately the 'Trial version' message didn't disappear.
- I have not revert back to demo, and keep that 'client' in the URL.
- The QA started testing, and reported that the Ck_Editor won't save the equation to DB because the changes not detected.
- I spent 2 days to try fixing this issue and solve it using 
- `checkEditorChanges = setInterval(function () `
- I came here also and post this.
- I saw you awesome response which gives me the key.
- I revert back my code to use demo again, and now it is working.

So, the issues now: 
- no trust on Wiris team.
- how to install the license.

**Comment by dcanetma** [comment]
Hello, @AmmarAlhabibACD 

Our Sales team is already in touch with you regarding the "Trial version" message.

As for the onChange issue, as mentioned hera and on a ticket opened with our Support Team, it is fixed in the /demo URL where version 7.26 is deployed.

The /client context runs a previous version.

Please note that, on a trial stage, the "Trial version" message shows both on /demo and /client. "Trial version" messages are to be removed by our Sales Team.

Kind regards,
